Add FAQ: Why am I missing required field `serviceName` during install?
User may receive the following error when executing `helm install ...`:

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec): missing required field "serviceName" in io.k8s.api.apps.v1.StatefulSetSpec

This is due to the requirement to define at least one service in
`values.yaml` prior to an install. Added FAQ to README.md to address
this question.